runmode: debug               # 开发模式, debug, release, test
addr: :6662                 # HTTP绑定端口
name: saiGo              # API Server的名字
url: http://127.0.0.1:6662  # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数
log:
  writers: file
  logger_level: DEBUG
  logger_file: log/saiGo.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backuo_count: 7
db:
  name: sai_go
  addr: 127.0.0.1:3308
  username: root
  password: 